/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("http://repo.e-iceblue.com/nexus/content/groups/public")

        // isAllowInsecureProtocol = true
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-jersey:2.4.2")
    implementation("org.springframework.boot:spring-boot-starter-web:2.4.2")
    implementation("org.jsoup:jsoup:1.10.2")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.4.2")
    compileOnly("org.projectlombok:lombok:1.18.24")
}

group = "com.example.bbk"
version = "0.0.1-SNAPSHOT"
description = "demo"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
